### ISSUE TITLE
External Reboot via web API unclear

### ISSUE THREAD

**Issue by rubenkr** [schmurtzm/RFLink32-For-Sonoff-RF-Bridge#6]
Hi @schmurtzm,
I am loving your project and running it on a Tasmota RF Bridges to reuse old RF-Door sensor to physical track incoming parcel.

However I found that not all sensor activities are recognized and could be fixed by manually rebooting the receiving RF Bridge.

I am now trying to soft reboot the device every evening or so via Node-Red or Home-Assistant. In the Wiki you are describing a web API to reboot the device. Could you please give an example how to use a POST command to execute a reboot over HTTP?

Thank you so much !!

**Comment by danielk117** [comment]
According to `12_Portal.cpp:247` it should be a GET against `http://hostname-or-ip/api/reboot`.

**Comment by rubenkr** [comment]
@danielk117 hell you are a genius ! it works. Thank you very much !
